openapi: 3.0.3

info:
  title: BD Systems API
  description: API para gerenciamento de empresas, obras e máquinas.
  version: 1.0.0

tags:
  - name: Authentication
    description: Cadastro e autenticação de usuários
  - name: Employee
    description: Cadastro de funcionários

paths:
  /api/auth/register:
    $ref: './auth/openapi.yml#/paths/~1api~1auth~1register'
  /api/auth/login:
    $ref: './auth/openapi.yml#/paths/~1api~1auth~1login'
  /api/auth/logout:
    $ref: './auth/openapi.yml#/paths/~1api~1auth~1logout'
  /api/employees:
    $ref: './employee/openapi.yml#/paths/~1api~1employees'
