ALTER TABLE users
    ADD COLUMN phone_number VARCHAR(255),
    ADD COLUMN document_number VARCHAR(255),
    ADD COLUMN birth_date DATE,
    ADD COLUMN active BOOLEAN NOT NULL DEFAULT TRUE,
    ADD COLUMN created_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN updated_at TIMESTAMP;
